# Generated by Django 5.2 on 2025-04-13 11:36

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default={}, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('recursive', models.BooleanField(default=False)),
                ('page', models.ForeignKey(help_text='Select page to export.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cms.page', verbose_name='CMS Page.')),
            ],
            options={
                'verbose_name': 'Page Export',
            },
        ),
        migrations.CreateModel(
            name='PageImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default={}, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('parent_page', models.ForeignKey(blank=True, help_text='Select parent page - pages to import are created below.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cms.page', verbose_name='Parent CMS Page')),
            ],
            options={
                'verbose_name': 'Page Import',
            },
        ),
    ]
